# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Blog in the Machine
logo: "/assets/images/favicon-48x48.png"
email: info.bloginthemachine@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog in the Machine is a blog authored by me, pandaniel. This is 
  intended as a place where I talk about a variety of tabletop roleplaying 
  games, but mostly the Sine Nomine Publishing ones.
baseurl: "/bloginthemachine" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bloginDmachine
github_username:  pandanielxd

# Build settings
markdown: GFM
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
og_image: /assets/images/web-app-manifest-192x192.png
repository: "pandanielxd/bloginthemachine"
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.
plugins:
  - jekyll-feed
  - jekyll-include-cache
search: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      toc: true
      toc_sticky: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
      
# Site Author
author:
  name        : "pandaniel"
  bio         : "*Blog in the Machine* webmaster and author."
  avatar      : "https://i.imgur.com/kBdiZ28.png"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info.bloginthemachine@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bloginDmachine/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bloginDmachine/"

# Reading Files
include:
  - _sass
  - _pages
  - _includes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README
  - .obsidian/
  - .space/
  - Tags/
  - .makemd/
  - todo.md